#pragma once


namespace geoneric {

enum class MessageId {

    UNKNOWN_ERROR,

    IO_ERROR,
    DOES_NOT_EXIST,
    CANNOT_BE_READ,
    DOES_NOT_CONTAIN_FEATURE,
    DOES_NOT_CONTAIN_ATTRIBUTE,
    UNSUPPORTED_VALUE_TYPE,

    ERROR_PARSING,
    ERROR_PARSING_STATEMENT,

    // UNSUPPORTED_EXPRESSION,
    UNSUPPORTED_LANGUAGE_CONSTRUCT,
    UNDEFINED_IDENTIFIER,
    UNDEFINED_OPERATION,

    ERROR_VALIDATING

};

}
