environment:
    FERN_CMAKE_ARGUMENTS: -DBOOST_ROOT=C:\projects\fern\boost.1.59.0.0\lib\native -DFERN_BUILD_ALGORITHM:BOOL=TRUE -DFERN_BUILD_DOCUMENTATION:BOOL=FALSE -DFERN_BUILD_TEST:BOOL=TRUE

platform:
    # - x86
    - x64

configuration:
    - Debug
      # - Release

matrix:
    fast_finish: true

install:
    - git submodule update --init --recursive
    # - nuget install boost-vc140 -Version 1.59.0
    - nuget install boost -Version 1.59.0
    # - nuget install boost_filesystem-vc140 -Version 1.59.0
    # - nuget install boost_system-vc140 -Version 1.59.0
    # - nuget install boost_timer-vc140 -Version 1.59.0
    # - nuget install boost_unit_test_framework-vc140 -Version 1.59.0

before_build:
    - dir
    - dir /s /b boost.1.59.0.0
    # - dir /s /b boost_filesystem-vc140.1.59.0.0
    - md build
    - cd build
    - cmake --version
    - cmake %FERN_CMAKE_ARGUMENTS% -G"Visual Studio 14 Win64" ..

build:
    project: fern.sln
    parallel: true
    verbosity: normal
