environment:
    FERN_CMAKE_ARGUMENTS: -DBOOST_ROOT=C:\projects\fern\boost.1.59.0.0\lib\native -DFERN_BUILD_ALGORITHM:BOOL=TRUE -DFERN_BUILD_DOCUMENTATION:BOOL=FALSE -DFERN_BUILD_TEST:BOOL=TRUE

    matrix:
        - GENERATOR: "Visual Studio 14 Win64"
          CONFIG: Debug

platform:
    # - x86
    - x64

# configuration:
#     - Debug
#       # - Release

matrix:
    fast_finish: true

# Copy libs to boost.1.59.0.0\lib\native\lib, for CMake to pick up.
install:
    - git submodule update --init --recursive
    - nuget install boost -Version 1.59.0
    - nuget install boost_filesystem-vc140 -Version 1.59.0
    - nuget install boost_system-vc140 -Version 1.59.0
    - nuget install boost_timer-vc140 -Version 1.59.0
    - nuget install boost_unit_test_framework-vc140 -Version 1.59.0
    - mkdir boost.1.59.0.0\lib\native\lib
    - copy boost_filesystem-vc140.1.59.0.0\lib\native\address-model-64\lib\* boost.1.59.0.0\lib\native\lib
    - copy boost_system-vc140.1.59.0.0\lib\native\address-model-64\lib\* boost.1.59.0.0\lib\native\lib
    - copy boost_timer-vc140.1.59.0.0\lib\native\address-model-64\lib\* boost.1.59.0.0\lib\native\lib
    - copy boost_unit_test_framework-vc140.1.59.0.0\lib\native\address-model-64\lib\* boost.1.59.0.0\lib\native\lib


build_script:
    - cmake -G"%GENERATOR%" %FERN_CMAKE_ARGUMENTS% -H . -B build
    - cmake --build build --config "%CONFIG%"

test_script:
    - cd build
    - ctest -VV -C "%CONFIG%"


# before_build:
#     - dir
#     - md build
#     - cd build
#     - cmake --version
#     - cmake %FERN_CMAKE_ARGUMENTS% -G"Visual Studio 14 Win64" ..
#     - dir
# 
# build:
#     project: build\ALL_BUILD.vcxproj  # Fern.sln
#     parallel: true
#     verbosity: normal
