# TODO Make it possible to only configure those things that are needed for
#      fern.algorithm. Instead of everything.

# Should we only configure for use of fern.algorithm?
OPTION(FERN_ALGORITHM_ONLY FALSE)

IF(FERN_ALGORITHM_ONLY)
    SET(FERN_BOOST_REQUIRED TRUE)
    SET(FERN_BOOST_COMPONENTS filesystem system timer unit_test_framework)
    SET(FERN_EXPAT_REQUIRED FALSE)
    SET(FERN_XSD_REQUIRED FALSE)
    SET(FERN_GDAL_REQUIRED FALSE)
    SET(FERN_HDF5_REQUIRED FALSE)
    SET(FERN_NETCDF_REQUIRED FALSE)
    SET(FERN_PYTHON_LIBS_REQUIRED FALSE)
    SET(FERN_READLINE_REQUIRED FALSE)
    SET(FERN_LOKI_REQUIRED FALSE)
ELSE()
    SET(FERN_BOOST_REQUIRED TRUE)
    SET(FERN_BOOST_COMPONENTS filesystem system timer unit_test_framework)
    SET(FERN_EXPAT_REQUIRED TRUE)
    SET(FERN_XSD_REQUIRED TRUE)
    SET(FERN_GDAL_REQUIRED TRUE)
    SET(FERN_HDF5_REQUIRED TRUE)
    SET(FERN_NETCDF_REQUIRED TRUE)
    SET(FERN_PYTHON_LIBS_REQUIRED TRUE)
    SET(FERN_READLINE_REQUIRED TRUE)
    SET(FERN_LOKI_REQUIRED TRUE)
ENDIF()
