IF(DEFINED ENV{PCRTEAM_PLATFORM})
    # Configure search path to find packages.
    SET(CMAKE_PREFIX_PATH
        ${CMAKE_PREFIX_PATH}
        $ENV{PCRTEAM_PLATFORM}
        $ENV{PCRTEAM_PLATFORM}/python-2.7.6
    )
ENDIF()


# Configure and find packages, configure project. ------------------------------
IF(FERN_BOOST_REQUIRED)
    SET(Boost_USE_STATIC_LIBS OFF)
    SET(Boost_USE_STATIC_RUNTIME OFF)
    ADD_DEFINITIONS(
        # Use dynamic libraries.
        -DBOOST_ALL_DYN_LINK
        # Prevent auto-linking.
        -DBOOST_ALL_NO_LIB

        # # No deprecated features.
        # -DBOOST_FILESYSTEM_NO_DEPRECATED

        # -DBOOST_CHRONO_DONT_PROVIDE_HYBRID_ERROR_HANDLING
        # -DBOOST_CHRONO_HEADER_ONLY

        # -DBOOST_DISABLE_ASSERTS  <---- !!!
    )
    FIND_PACKAGE(Boost REQUIRED
        COMPONENTS ${FERN_REQUIRED_BOOST_COMPONENTS})
    INCLUDE_DIRECTORIES(
        SYSTEM
        ${Boost_INCLUDE_DIRS}
    )
    LIST(APPEND FERN_EXTERNAL_LIBRARIES
        ${Boost_FILESYSTEM_LIBRARY}
        ${Boost_PROGRAM_OPTIONS_LIBRARY}
        ${Boost_SYSTEM_LIBRARY}
    )
ENDIF()
FIND_PACKAGE(Doxygen)
IF(FERN_EXPAT_REQUIRED)
    FIND_PACKAGE(EXPAT REQUIRED)
    INCLUDE_DIRECTORIES(
        SYSTEM
        ${EXPAT_INCLUDE_DIRS}
    )
ENDIF()
IF(FERN_GDAL_REQUIRED)
    FIND_PACKAGE(GDAL REQUIRED)
    INCLUDE_DIRECTORIES(
        SYSTEM
        ${GDAL_INCLUDE_DIRS}
    )
    LIST(APPEND FERN_EXTERNAL_LIBRARIES
        ${GDAL_LIBRARIES}
    )
ENDIF()
IF(FERN_HDF5_REQUIRED)
    SET(HDF5_USE_STATIC_LIBRARIES OFF)
    FIND_PACKAGE(HDF5 REQUIRED
        COMPONENTS C CXX HL)
    INCLUDE_DIRECTORIES(
        SYSTEM
        ${HDF5_INCLUDE_DIRS}
    )
    LIST(APPEND FERN_EXTERNAL_LIBRARIES
        ${HDF5_LIBRARIES}
    )
ENDIF()
IF(FERN_LOKI_REQUIRED)
    FIND_PACKAGE(Loki REQUIRED)
ENDIF()
IF(FERN_NETCDF_REQUIRED)
    FIND_PACKAGE(NetCDF REQUIRED)
ENDIF()
IF(FERN_PYTHON_LIBS_REQUIRED)
    SET(Python_ADDITIONAL_VERSIONS "2.7")
    FIND_PACKAGE(PythonLibs REQUIRED)
    INCLUDE_DIRECTORIES(
        SYSTEM
        ${PYTHON_INCLUDE_DIRS}
    )
    LIST(APPEND FERN_EXTERNAL_LIBRARIES
        ${PYTHON_LIBRARIES}
    )
ENDIF()
IF(FERN_READLINE_REQUIRED)
    FIND_PACKAGE(Readline REQUIRED)
    INCLUDE_DIRECTORIES(
        SYSTEM
        ${READLINE_INCLUDE_DIR}
    )
ENDIF()
IF(FERN_XSD_REQUIRED)
    FIND_PACKAGE(XSD REQUIRED)
    INCLUDE_DIRECTORIES(
        SYSTEM
        ${XSD_INCLUDE_DIRS}
    )
ENDIF()
