FIND_PATH(LOKI_INCLUDE_DIR loki/Typelist.h)
FIND_LIBRARY(LOKI_LIBRARY NAMES loki)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(Loki DEFAULT_MSG LOKI_INCLUDE_DIR
    LOKI_LIBRARY)

MARK_AS_ADVANCED(LOKI_INCLUDE_DIR LOKI_LIBRARY)
