CONFIGURE_FILE(
    ${CMAKE_CURRENT_SOURCE_DIR}/conf.py.in
    ${CMAKE_CURRENT_BINARY_DIR}/conf.py
)
CONFIGURE_FILE(
    # Don't name the new file Makefile, as it conflicts with the CMake generated
    # file.
    ${CMAKE_CURRENT_SOURCE_DIR}/Makefile.in
    ${CMAKE_CURRENT_BINARY_DIR}/Makefile-sphinx
)

FOREACH(NAME ${SPHINX_SOURCES})
    SET(SPHINX_SOURCE ${CMAKE_CURRENT_SOURCE_DIR}/${NAME})
    SET(COPIED_SPHINX_SOURCE ${CMAKE_CURRENT_BINARY_DIR}/${NAME})
    ADD_CUSTOM_COMMAND(
        OUTPUT ${COPIED_SPHINX_SOURCE}
        COMMAND ${CMAKE_COMMAND} -E copy ${SPHINX_SOURCE}
            ${COPIED_SPHINX_SOURCE}
        DEPENDS ${SPHINX_SOURCE}
    )
    LIST(APPEND COPIED_SPHINX_SOURCES ${COPIED_SPHINX_SOURCE})
ENDFOREACH()

FOREACH(NAME _build _static _templates)
    ADD_CUSTOM_COMMAND(
        OUTPUT ${CMAKE_CURRENT_BINARY_DIR}/${NAME}
        COMMAND ${CMAKE_COMMAND} -E ${CMAKE_MAKE_PROGRAM}
            ${CMAKE_CURRENT_BINARY_DIR}/${NAME}
    )
ENDFOREACH()

SET(SPHINX_SPHINXOPTS "-q -W")
# SET(SPHINX_PAPER a4)

ADD_CUSTOM_COMMAND(
    OUTPUT ${CMAKE_CURRENT_BINARY_DIR}/_build/html/index.html
    COMMAND ${CMAKE_MAKE_PROGRAM} SPHINXOPTS=${SPHINX_SPHINXOPTS}
        -C ${CMAKE_CURRENT_BINARY_DIR}
        -f Makefile-sphinx html
    DEPENDS
        ${CMAKE_CURRENT_BINARY_DIR}/conf.py
        ${CMAKE_CURRENT_BINARY_DIR}/Makefile-sphinx
        ${CMAKE_CURRENT_BINARY_DIR}/_build
        ${CMAKE_CURRENT_BINARY_DIR}/_static
        ${CMAKE_CURRENT_BINARY_DIR}/_templates
        ${COPIED_SPHINX_SOURCES}
)

ADD_CUSTOM_TARGET(${SPHINX_TARGET} ALL
  DEPENDS ${CMAKE_CURRENT_BINARY_DIR}/_build/html/index.html
)
