# vim:syntax=sh

# Requires:
# - DEVELOPMENT_ROOT
# Sets:
# - DEVENV_BRANCH
# - RANALLY

# Set branches.
export DEVENV_BRANCH=trunk

_devEnv="$DEVELOPMENT_ROOT/projects/DevEnv-$DEVENV_BRANCH"
_personalConfiguration="$_devEnv/configuration/personal/Kor"

# Load common settings and utility functions.
# source "$_personalConfiguration/Profiles/Utils.sh"
source "$_personalConfiguration/Profiles/common" $1
# setPcrTeamExternIfNotSetAlready $DEVENV_BRANCH

# Load project settings.
source "$_personalConfiguration/Profiles/DevEnv"

export RANALLY=$projects/Ranally

export CDPATH=$CDPATH:$RANALLY/Sources

_baseName=`basename $RANALLY`

export PATH=$OBJECTS/$_baseName/bin:$PATH

unset _basename
unset _devEnv
unset _personalConfiguration

cd $RANALLY
setPromptForProject Ranally $BUILD_TYPE
