# vim:syntax=sh

export DEVENV_BRANCH=master

_devenv="$PROJECTS/`\ls $PROJECTS | \grep -i \"^devenv$\"`"
_profiles="$_devenv/configuration/profiles"
unset _devenv

source "$_profiles/common" $1
source "$_profiles/DevEnv"
unset _profiles

export RANALLY="$PROJECTS/`\ls $PROJECTS | \grep -i \"^ranally$\"`"

_basename=`basename $RANALLY`
export PATH=$RANALLY/environment/scripts:$OBJECTS/$_basename/bin:$PATH
unset _basename

# Override to make use of our own built, new gcc.
export CC=/opt/gcc-4.8/bin/gcc
export CXX=/opt/gcc-4.8/bin/g++
export LD_LIBRARY_PATH=/opt/gcc-4.8/lib64:$LD_LIBRARY_PATH

cd $RANALLY
setPromptForProject Ranally $BUILD_TYPE
