# vim:syntax=sh

export DEVENV_BRANCH=master

_devenv="$PROJECTS/`\ls $PROJECTS | \grep -i \"^devenv$\"`"
_profiles="$_devenv/configuration/profiles"
unset _devenv

source "$_profiles/common" $1
source "$_profiles/DevEnv"
unset CMAKE_MODULE_PATH
unset _profiles

export FERN="$PROJECTS/`\ls $PROJECTS | \grep -i \"^fern$\"`"

_basename=`basename $FERN`
export PATH=$FERN/environment/scripts:$OBJECTS/$_basename/bin:$PATH
unset _basename

export FERN_CMAKE_ARGUMENTS="-DFERN_ALGORITHM_ONLY=TRUE"

cd $FERN
setPromptForProject fern $BUILD_TYPE

# Since there is a command named fern, we need to get rid of the alias.
unalias fern 2>/dev/null

cd sources/fern
